FROM quay.io/centos-bootc/centos-bootc:stream9
ADD etc etc

RUN dnf clean all
ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache
RUN dnf -y copr enable @redhat-et/flightctl-dev centos-stream-9-x86_64

RUN dnf update -y && dnf install -y flightctl-agent && \
    systemctl enable flightctl-agent.service
## Uncomment to add your own ssh key
# COPY flightctl_rsa.pub /usr/etc-system/root.keys
# RUN touch /etc/ssh/sshd_config.d/30-auth-system.conf; \
#       mkdir -p /usr/etc-system/; \
#       echo 'AuthorizedKeysFile /usr/etc-system/%u.keys' >> /etc/ssh/sshd_config.d/30-auth-system.conf; \
#       chmod 0600 /usr/etc-system/root.keys
# VOLUME /var/roothome

## Add your flightctl configuration and certificates

RUN useradd -ms /bin/bash user && \
        echo "user:user" | chpasswd && \
        echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
        echo "10.46.46.54 agent-api.apps.ocp-edge-cluster-0.qe.lab.redhat.com" > /etc/hosts


ADD agentconfig.yaml /etc/flightctl/config.yaml

