apiVersion: v1alpha1
kind: Fleet
metadata:
  name: test-templating
spec:
  selector:
    matchLabels:
      fleet: test-templating
  template:
    metadata:
      labels:
        fleet: test-templating
    spec:
      os:
        image: quay.io/sserafin/flightctl-agent-centos:latest 
      config: []
      resources:
        - monitorType: CPU
          alertRules:
            - severity: Warning
              duration: 10m
              percentage: 60
              description: 'CPU load is above 50% for more than 10 minutes'
          samplingInterval: 50s
      systemd:
        matchPatterns:
          - chronyd.service

