apiVersion: v1alpha1
kind: Fleet
metadata:
  name: test
spec:
  selector:
    matchLabels:
      fleet: test
  template:
    metadata:
      labels:
        fleet: test
    spec:
      os:
        image: quay.io/redhat/rhde:{{index .device.metadata.labels `team` }}
      config:
        - name: base
          configType: GitConfigProviderSpec
          gitRef:
            repository: tests
            targetRevision: main
            path: /
        - name: motd-update
          configType: InlineConfigProviderSpec
          inline:
            ignition:
              version: 3.4.0
            storage:
              files:
                - contents:
                    source: >-
                      data:,i{{index .device.metadata.labels `team` }}Team%20{{ index .device.metadata.labels `team` }}%20is%20managed%20by%20flightctl.%0A
                  mode: 422
                  overwrite: true
                  path: "/etc/motd"
      resources:
        - monitorType: CPU
          alertRules:
            - severity: Warning
              duration: 10m
              percentage: 60
              description: 'CPU load is above 50% for more than 10 minutes'
          samplingInterval: 50s
      systemd:
        matchPatterns:
          - chronyd.service

