version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Containerfile
    container_name: flask-webapp
    ports:
      - "4000:4000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app:Z  # Ensure the correct SELinux context if necessary

