apiVersion: v1alpha1
kind: Fleet
metadata:
  name: test-templating
spec:
  selector:
    matchLabels:
      fleet: test-templating
  template:
    metadata:
      labels:
        fleet: test-templating
    spec:
      os:
        image: 192.168.1.15:5000/flightctl-device:base
      config:
        - name: simple-app
          configType: InlineConfigProviderSpec
          inline:
            ignition:
              version: 3.4.0
            storage:
              files:
                - contents:
                    source: >-
                      data:text/plain;base64,dmVyc2lvbjogJzMuOCcKCnNlcnZpY2VzOgogIHdlYjoKICAgIGJ1aWxkOgogICAgICBjb250ZXh0OiAuCiAgICAgIGRvY2tlcmZpbGU6IENvbnRhaW5lcmZpbGUKICAgIGNvbnRhaW5lcl9uYW1lOiBmbGFzay13ZWJhcHAKICAgIHBvcnRzOgogICAgICAtICI0MDAwOjQwMDAiCiAgICBlbnZpcm9ubWVudDoKICAgICAgLSBGTEFTS19BUFA9YXBwLnB5CiAgICAgIC0gRkxBU0tfRU5WPWRldmVsb3BtZW50CiAgICB2b2x1bWVzOgogICAgICAtIC46L2FwcDpaICAjIEVuc3VyZSB0aGUgY29ycmVjdCBTRUxpbnV4IGNvbnRleHQgaWYgbmVjZXNzYXJ5Cgo=
                  mode: 422
                  overwrite: true
                  path: "/var/run/flightctl/compose/podman-compose.yml"
      resources:
        - monitorType: CPU
          alertRules:
            - severity: Warning
              duration: 10m
              percentage: 60
              description: 'CPU load is above 50% for more than 10 minutes'
          samplingInterval: 50s
      systemd:
        matchPatterns:
          - chronyd.service

