version: '3.8'

services:
  web:
    image: python:3.9-slim  # Base image with Python installed
    container_name: simple-web-app
    working_dir: /app
    volumes:
      - ./app:/app  # Mount the local `app` directory to `/app` inside the container
    ports:
      - "4000:4000"  # Map port 4000 on the VM to port 4000 inside the container
    environment:
      FLASK_ENV: development  # Set environment variable
    command: python app.py  # Command to run the Flask app

    # Optional restart policy
    restart: unless-stopped

# networks:
#   default:
#     driver: bridge

