apiVersion: v1alpha1
kind: Device
metadata:
  name: f68dfb5f5d2cdbb9339363b7f19f3ce269d75650bdc80004f1e04293a8ef9c4
  labels:
    fleet: none
spec:
  os:
    image: quay.io/redhat/rhde:9.2
  config:
    - name: acm-crd
      configType: HttpConfigProviderSpec
      httpRef:
        repository: tests
        suffix: /agent-registration/crds/v1
        filePath: /tmp/device-config.yaml
