apiVersion: v1alpha1
kind: Fleet
metadata:
  annotations:
  labels: {}
  name: no-template
spec:
  selector:
    matchLabels:
      "no": template
  template:
    metadata:
      labels:
        fleet: no-template
    spec:
      config:
        - name: test-crd
          configType: HttpConfigProviderSpec
          httpRef:
            repository: http
            suffix: /agent-registration/crds/v1
            filePath: /tmp/klusterlet/crd.yaml
        - name: motd-update
          configType: InlineConfigProviderSpec
          inline:
            ignition:
              version: 3.4.0
            storage:
              files:
                - contents:
                    source: >-
                      data:,iTeam%20{{ device.metadata.name }}%20is%20managed%20by%20flightctl.%0A
                  mode: 422
                  overwrite: true
                  path: "/etc/motd"
      os:
        image: quay.io/sserafin/flightctl-agent-centos     
