apiVersion: v1alpha1
kind: Fleet
metadata:
  name: test
spec:
  selector:
    matchLabels:
      fleet: test
  template:
    metadata:
      labels:
        fleet: test
    spec:
      os:
        image: 192.168.1.101:5000/flightctl-device:v2
      config:
        config:    
          - name: test-crd           
            configType: HttpConfigProviderSpec           
            httpRef:             
              repository: tests             
              suffix: /agent-registration/crds/v1             
              filePath: /tmp/klusterlet/crd.yaml
        - monitorType: CPU
          alertRules:
            - severity: Warning
              duration: 10m
              percentage: 60
              description: 'CPU load is above 50% for more than 10 minutes'
          samplingInterval: 50s
      systemd:
        matchPatterns:
          - chronyd.service
