apiVersion: v1alpha1
kind: Fleet
metadata:
  name: second
spec:
  selector:
    matchLabels:
      fleet: second
  template:
    metadata:
      labels:
        fleet: second
    spec:
      os:
        image: 192.168.1.140:5000/flightctl-device:base
      config:
        - name: base
          configType: GitConfigProviderSpec
          gitRef:
            repository: tests
            targetRevision: main
            path: "/fleet-test.yaml"
        - configType: InlineConfigProviderSpec
          inline:
            - content: "This system is managed by flightctl"
              mode: 422
              overwrite: true
              path: /etc/motd
      resources:
        - monitorType: CPU
          alertRules:
            - severity: Warning
              duration: 10m
              percentage: 60
              description: 'CPU load is above 50% for more than 10 minutes'
          samplingInterval: 50s
      systemd:
        matchPatterns:
          - chronyd.service

