apiVersion: v1alpha1
kind: Fleet
metadata:
  name: my-fleet
spec:
  selector:
    matchLabels:
      key: value
  template:
    metadata:
      labels:
        fleet: my-fleet
    spec:
      os:
        image: quay.io/sserafin/flightctl-agent-centos
      config:
        - configType: GitConfigProviderSpec
          gitRef:
            mountPath: /var/home/user
            path: "/{{ device.metadata.labels[config] }}"
            repository: test
            targetRevision: main
          name: test-gi
        - name: motd-update
          configType: InlineConfigProviderSpec
          inline:
            ignition:
              version: 3.4.0
            storage:
              files:
                - contents:
                    source: >-
                      data:,iTeam%20{{ device.metadata.name }}%20is%20managed%20by%20flightctl.%0A
                  mode: 422
                  overwrite: true
                  path: "/etc/motd"
      systemd:
        matchPatterns:
          - chronyd.service
