apiVersion: v1alpha1
kind: Fleet
metadata:
  name: my-fleet
spec:
  selector:
    matchLabels:
      key: value
  template:
    metadata:
      labels:
        fleet: my-fleet
    spec:
      os:
        image: 192.168.1.15:5000/flightctl-device:base
      config:
        - name: v2
          configType: GitConfigProviderSpec
          gitRef:
            repository: tests
            targetRevision: main
            path: "/{{ .Name }}"
        - name: motd-update
          configType: InlineConfigProviderSpec
          inline:
            ignition:
              version: 3.4.0
            storage:
              files:
                - contents:
                    source: >-
                      data:,iTeam%20{{ .Labels["team"] }}%20is%20managed%20by%20flightctl.%0A
                  mode: 422
                  overwrite: true
                  path: "/etc/motd"
      resources:
        - monitorType: CPU
          alertRules:
            - severity: Warning
              duration: 10m
              percentage: 60
              description: 'CPU load is above 50% for more than 10 minutes'
          samplingInterval: 50s
      systemd:
        matchPatterns:
          - chronyd.service
