---
- name: Install flightctl deploy
  hosts: localhost
  remote_user: kni
  gather_facts: true
  vars:
    version: "latest"
    kubeconfig_path: "/home/kni/clusterconfigs/auth/kubeconfig"
    values_file: "/home/kni/flightctl/deploy/helm/flightctl/values.yaml"
    flightctl_image_url: "oci://quay.io/flightctl/charts/flightctl"
    flightctl_namespace: "flightctl"
    api_url: "https://api.apps.ocp-edge-cluster-0.qe.lab.redhat.com"
    ansible_user: kni
  environment:
    PATH: "/usr/local/bin:/usr/bin/:/usr/local/go/bin:{{ ansible_env.PATH }}"
    KUBECONFIG: "{{ kubeconfig_path }}"
  tasks:
    - name: Delete flightctl namespace
      ansible.builtin.shell: |
        oc delete namespace flightctl
      ignore_errors: true

    - name: Install flightctl with Helm
      ansible.builtin.shell: |
        helm install  --version {{ version }} --namespace {{ flightctl_namespace }} --create-namespace flightctl {{ flightctl_image_url }} --values {{ values_file }} --set global.target=acm  --set global.auth.insecureSkipTlsVerify=true --set kv.image.image=quay.io/sclorg/redis-7-c9s  --set db.storage.size=30Gi
      args:
        chdir: /home/kni/flightctl
      ignore_errors: true

    - name: Verify devices and pods {{ flightctl_namespace }}
      ansible.builtin.shell: |
        oc wait --for=condition=Available deployment --all -n flightctl --timeout=300s

    - name: Build flightctl cli
      ansible.builtin.command: |
        make
      args:
        chdir: /home/kni/flightctl
