---
- name: Install flightctl deploy
  hosts: "{{ 'provisionhost[0]' if groups.get('provisionhost') else 'localhost' }}"
  remote_user: kni
  gather_facts: true
  vars:
    version: latest
    ui_version: "latest"
    kubeconfig_path: "/home/kni/clusterconfigs/auth/kubeconfig"
    values_file: "/home/kni/flightctl/deploy/helm/flightctl/values.yaml"
    flightctl_image_url: "oci://quay.io/flightctl/charts/flightctl"
    flightctl_ui_image_url: "oci://quay.io/flightctl/charts/flightctl-ocp-ui"
    flightctl_namespace: "flightctl"
    api_url: "https://api.apps.ocp-edge-cluster-0.qe.lab.redhat.com"
    ansible_user: kni
  environment:
    PATH: "/usr/local/bin:/usr/bin/:/usr/local/go/bin:{{ ansible_env.PATH }}"
    KUBECONFIG: "{{ kubeconfig_path }}"
  tasks:
    - name: Provision a 60Gi persistent volume for the db pod
      ansible.builtin.shell: |
        PV_NAME=$(oc get pv --no-headers | awk '$3 == "RWO"' | awk '$5 == "Available" {print $1; exit}')
        oc patch pv $PV_NAME --type merge -p '{"spec": {"capacity": {"storage": "60Gi"}}}'
      ignore_errors: true

    - name: Delete flightctl namespace
      ansible.builtin.shell: |
        oc delete namespace flightctl
      ignore_errors: true

    - name: Install flightctl with Helm
      ansible.builtin.shell: |
        helm install  --version {{ version }} --namespace {{ flightctl_namespace }} --create-namespace flightctl {{ flightctl_image_url }} --values {{ values_file }} --set ui.image.tag={{ ui_version }} --set  prometheus.enabled=false --set global.target=acm --set global.storageClassName=standard --set global.auth.insecureSkipTlsVerify=true 
      args:
        chdir: /home/kni/flightctl
      ignore_errors: true

    - name: Verify devices and pods {{ flightctl_namespace }}
      ansible.builtin.shell: |
        oc wait --for=condition=Ready pod --all -n {{ flightctl_namespace }} --timeout=300s --field-selector=status.phase=Running

    - name: Retrieve API pod name
      ansible.builtin.shell: |
        oc get pod -n flightctl -l flightctl.service=flightctl-api --no-headers -o custom-columns=":metadata.name" | head -1
      register: api_pod_name

    - name: Copy certs from API pod
      ansible.builtin.shell: |
        oc exec -n flightctl {{ api_pod_name.stdout }} -- cat /root/.flightctl/certs/ca.crt > ca.crt
      args:
        chdir: /home/kni/flightctl

    - name: Build flightctl cli
      ansible.builtin.command: |
        make
      args:
        chdir: /home/kni/flightctl

