---
- name: Install flightctl deploy
  hosts: "{{ 'provisionhost[0]' if groups.get('provisionhost') else 'localhost' }}"
  remote_user: kni
  gather_facts: true
  vars:
    kubeconfig_path: "/home/kni/clusterconfigs/auth/kubeconfig"
    values_file: "/home/kni/flightctl/deploy/helm/flightctl/myvalues.yaml"
    flightctl_image_url: "oci://quay.io/flightctl/charts/flightctl"
    flightctl_ui_image_url: "oci://quay.io/flightctl/charts/flightctl-ocp-ui"
    flightctl_namespace: "flightctl"
    flightctl_version: "0.2.0-39-g597deaf"
    flightctl_ui_version: "0.2.0-11-ge8c643e"
    api_url: "https://api.apps.ocp-edge-cluster-0.qe.lab.redhat.com"
    ca_file: "~/.flightctl/certs/ca.crt"
    ansible_user: kni
  environment:
    PATH: "/usr/local/bin:/usr/bin/:/usr/local/go/bin:{{ ansible_env.PATH }}"
    KUBECONFIG: "{{ kubeconfig_path }}"
  tasks:
    - name: Install flightctl with Helm
      ansible.builtin.shell: |
        helm install --version={{ flightctl_version }} --namespace {{ flightctl_namespace }} --create-namespace flightctl {{ flightctl_image_url }} --values {{ values_file }}
      args:
        chdir: /home/kni/flightctl
      ignore_errors: true

    - name: Verify devices and pods {{ flightctl_namespace }}
      ansible.builtin.shell: |
        oc wait --for=condition=Ready pod --all -n {{ flightctl_namespace }} --timeout=300s

    - name: Retrieve API pod name
      ansible.builtin.shell: |
        oc get pod -n flightctl -l flightctl.service=flightctl-api --no-headers -o custom-columns=":metadata.name" | head -1
      register: api_pod_name

    - name: Copy certs from API pod
      ansible.builtin.shell: |
        oc exec -n flightctl {{ api_pod_name.stdout }} -- cat /root/.flightctl/certs/ca.crt > ca.crt
      args:
        chdir: /home/kni/flightctl

    - name: Add git config
      ansible.builtin.command: |
        git config --global --add safe.directory /home/kni/flightctl
      args:
        chdir: /home/kni/flightctl

    - name: Install flightctl UI plugin with Helm
      ansible.builtin.shell: |
        helm upgrade --install --version={{ flightctl_ui_version }} --namespace {{ flightctl_namespace }} --create-namespace flightctl-ui {{ flightctl_ui_image_url }} --values {{ values_file }} --set-file flightctlUi.certs.ca=ca.crt
      args:
        chdir: /home/kni/flightctl
      ignore_errors: true

    - name: Verify devices and pods {{ flightctl_namespace }}
      ansible.builtin.shell: |
        oc wait --for=condition=Ready pod --all -n {{ flightctl_namespace }} --timeout=300s

    - name: Build flightctl cli
      ansible.builtin.command: |
        make
      args:
        chdir: /home/kni/flightctl

